#
# ~/.bashrc
#

# Set language to English
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"

# Set history size to infinite
export HISTSIZE="INFINITE"

# Enable ** (globstar) path matching
shopt -s globstar

# Add PS1 customization
. $(dirname $(readlink $HOME/.bashrc))/modules/ps1.sh

# Add Z for jumping directories
export _Z_CMD="j"
. $(dirname $(readlink $HOME/.bashrc))/modules/z.sh

# Add base16 colors
. $(dirname $(readlink $HOME/.bashrc))/modules/base16-tomorrow-night.sh

# Prompt for removal confirmation
alias rm='rm -i'

# Shorthand aliases for ls with flags
ls --color=auto &> /dev/null &&
alias ls="ls --color=auto" ||
alias ls="ls -G"
alias ll='ls -l'
alias la='ll -A'

# Don't get interupted by git misspelling!
alias gti=git
alias gi=git
alias gitk=git
alias gtik=git

# Editor settings
export EDITOR="emacs"
export VISUAL="emacs"

# Better tab completion. Not sure what bash version is needed for this.
bind 'set completion-ignore-case on'
bind 'set show-all-if-ambiguous on'
bind 'set colored-stats on'
bind 'set visible-stats on'
bind 'TAB:menu-complete'

# Hack necessary for the base16 color theme to work
# Preferably it would be set to the actual terminal emulator used (Alacritty),
# but there doesn't seem to be a valid 256 color theme for it
export TERM="xterm-256color"

# Add some host specific configuration, if available
if [ -f $(dirname $(readlink $HOME/.bashrc))/modules/${HOSTNAME}-specific.sh ]; then
   . $(dirname $(readlink $HOME/.bashrc))/modules/${HOSTNAME}-specific.sh
fi
