#
# ~/.bashrc
#

# Set language to English
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"

# Set history size to infinite
export HISTSIZE="INFINITE"

# Add custom binaries to path
export PATH=$PATH:${HOME}/.bash_binaries

# Enable ** (globstar) path matching
shopt -s globstar

# Add PS1 customization
. ${HOME}/.bash_modules/ps1.sh

# Add Z for jumping directories
export _Z_CMD="j"
. ${HOME}/.bash_modules/z.sh

# Add git completion
. ${HOME}/.bash_modules/git-completion.sh

# Add trash configuration
. ${HOME}/.bash_modules/trash.sh

# Add pass completion
. ${HOME}/.bash_modules/pass-completion.sh

# Add base16 colors
. ${HOME}/.bash_modules/base16-tomorrow-night.sh


# Prompt for removal confirmation
alias rm='rm -i'

# Shorthand aliases for ls with flags
ls --color=auto &> /dev/null &&
alias ls="ls --color=auto" ||
alias ls="ls -G"

alias ll='ls -l'
alias la='ll -A'

# Don't get interupted by git misspelling!
alias gti=git
alias gi=git
alias gitk=git
alias gtik=git

alias stack=docker-compose

# Editor settings
export EDITOR="emacs"
export VISUAL="emacs"

# Better tab completion. Not sure what bash version is needed for this.
bind 'set completion-ignore-case on'
bind 'set show-all-if-ambiguous on'
bind 'set colored-stats on'
bind 'set visible-stats on'
bind 'TAB:menu-complete'

# Ugh why. Not sure if I need this
export TERM="xterm-256color" 

# the following should be in system-specific.sh or something
cat /etc/motd

export PATH=$PATH:${HOME}/scripts
export BROWSER="docker exec firefox startfirefox"
[[ -z $DISPLAY && XDG_VTNR -eq 1 ]] && exec startx
